### ISSUE TITLE
attribute akka_version isn't defined

### ISSUE THREAD

**Issue by synox** [akka/akka-quickstart-java.g8#1]
I am running this on a windows 7 machine. What am I doing wrong?

	{ t }  » which sbt                                                                                                                                    /d/temp/t
	/cygdrive/c/Program Files (x86)/sbt/bin/sbt
	{ t }  » java -version                                                                                                                                /d/temp/t
	java version "1.8.0_112"
	Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
	Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)

	{ t }  » sbt new akka/akka-java-seed.g8                                                                                                               /d/temp/t
	[info] Set current project to t (in build file:/D:/temp/t/)
	SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
	SLF4J: Defaulting to no-operation (NOP) logger implementation
	SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

	Exiting due to error in the template
	File: D:\dev\apps\.babun\cygwin\tmp\giter8-6791571998485\src\main\g8\project\Dependencies.scala, context [anonymous] 4:27 internal error: org.stringtemplate.v4.compiler.STException: context [anonymous] 4:27 attribute akka_version isn't defined
	        at giter8.G8$STErrorHandler.runTimeError(g8.scala:110)
	        at giter8.G8$STErrorHandler.runTimeError(g8.scala:105)
	        at org.stringtemplate.v4.misc.ErrorManager.runTimeError(ErrorManager.java:133)
	        at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:193)
	        at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
	        at org.stringtemplate.v4.ST.write(ST.java:427)
	        at org.stringtemplate.v4.ST.render(ST.java:497)
	        at org.clapper.scalasti.ST.render(ST.scala:286)
	        at giter8.G8$.applyTemplate(g8.scala:102)
	        at giter8.G8$.write(g8.scala:154)
	        at giter8.G8$.write(g8.scala:138)
	        at giter8.G8$$anonfun$writeTemplates$2$$anonfun$apply$11.apply(g8.scala:396)
	        at giter8.G8$$anonfun$writeTemplates$2$$anonfun$apply$11.apply(g8.scala:396)
	        at scala.util.control.Exception$Catch$$anonfun$opt$1.apply(Exception.scala:118)
	        at scala.util.control.Exception$Catch$$anonfun$opt$1.apply(Exception.scala:118)
	        at scala.util.control.Exception$Catch.apply(Exception.scala:102)
	        at scala.util.control.Exception$Catch.opt(Exception.scala:118)
	        at giter8.G8$$anonfun$writeTemplates$2.apply(g8.scala:395)
	        at giter8.G8$$anonfun$writeTemplates$2.apply(g8.scala:386)
	        at scala.collection.immutable.Stream.foreach(Stream.scala:547)
	        at giter8.G8$.writeTemplates(g8.scala:386)
	        at giter8.G8$$anonfun$applyT$1.apply(g8.scala:256)
	        at giter8.G8$$anonfun$applyT$1.apply(g8.scala:249)
	        at scala.util.Either$RightProjection.flatMap(Either.scala:523)
	        at giter8.G8$.applyT(g8.scala:249)
	        at giter8.G8$.fromDirectory(g8.scala:62)
	        at giter8.JgitHelper$$anonfun$run$2.apply(JgitHelper.scala:67)
	        at giter8.JgitHelper$$anonfun$run$2.apply(JgitHelper.scala:66)
	        at scala.util.Either$RightProjection.flatMap(Either.scala:523)
	        at giter8.JgitHelper$.run(JgitHelper.scala:66)
	        at giter8.JgitHelper$.run(JgitHelper.scala:78)
	        at giter8.Giter8$$anonfun$2.apply(giter8.scala:34)
	        at giter8.Giter8$$anonfun$2.apply(giter8.scala:33)
	        at scala.Option.map(Option.scala:145)
	        at giter8.Giter8.run(giter8.scala:33)
	        at sbtgiter8resolver.Giter8TemplateResolver.run(Giter8TemplateResolver.scala:31)
	        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	        at java.lang.reflect.Method.invoke(Unknown Source)
	        at sbt.TemplateCommandUtil$.call(TemplateCommand.scala:68)
	        at sbt.TemplateCommandUtil$.sbt$TemplateCommandUtil$$runTemplate(TemplateCommand.scala:59)
	        at sbt.TemplateCommandUtil$$anonfun$2.apply(TemplateCommand.scala:45)
	        at sbt.TemplateCommandUtil$$anonfun$2.apply(TemplateCommand.scala:41)
	        at scala.collection.LinearSeqOptimized$class.find(LinearSeqOptimized.scala:100)
	        at scala.collection.immutable.List.find(List.scala:84)
	        at sbt.TemplateCommandUtil$.sbt$TemplateCommandUtil$$run(TemplateCommand.scala:41)
	        at sbt.TemplateCommandUtil$$anonfun$templateCommandParser$1.apply(TemplateCommand.scala:34)
	        at sbt.TemplateCommandUtil$$anonfun$templateCommandParser$1.apply(TemplateCommand.scala:28)
	        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	        at sbt.Command$.process(Command.scala:93)
	        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	        at sbt.State$$anon$1.process(State.scala:184)
	        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	        at sbt.MainLoop$.next(MainLoop.scala:96)
	        at sbt.MainLoop$.run(MainLoop.scala:89)
	        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	        at sbt.Using.apply(Using.scala:24)
	        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	        at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	        at sbt.StandardMain$.runManaged(Main.scala:57)
	        at sbt.xMain.run(Main.scala:29)
	        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	        at xsbt.boot.Launch$.run(Launch.scala:109)
	        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	        at xsbt.boot.Launch$.launch(Launch.scala:117)
	        at xsbt.boot.Launch$.apply(Launch.scala:18)
	        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	        at xsbt.boot.Boot$.main(Boot.scala:17)
	        at xsbt.boot.Boot.main(Boot.scala)

**Comment by ktoso** [comment]
No idea, should that work @eed3si9n ?

**Comment by raboof** [comment]
`sbt new akka/akka-quickstart-java.g8` should work - we don't refer to akka_version anywhere right now. Feel free to reopen when the problem appears to persist!
